server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 1800

spring:
  cache:
    type: caffeine

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  profiles:
    active:
    - dev
knife4j:
  enable: true

# 设置日志级别
logging:
  level:
    root: INFO