#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          my-client:
#            client-id: my-client
#            client-secret: my-secret
#            scope: read
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            client-name: My Client
#        provider:
#          my-provider:
#            authorization-uri: http://localhost:8080/oauth/authorize
#            token-uri: http://localhost:8080/oauth/token
#            user-info-uri: http://localhost:8080/oauth/userinfo
#            user-name-attribute: name
#
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/oauth/check_token
#logging:
#  level:
#    root: debug